name: Deploy

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.SERVER_APP_NAME }} 
          heroku_email: ${{ secrets.MY_HEROKU_EMAIL }}
          appdir: "server"
        env:
          HD_PORT:  3000
          HD_APP_BASE: server
          HD_PROCFILE: server/Procfile
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.CLIENT_APP_NAME }}
          heroku_email: ${{ secrets.MY_HEROKU_EMAIL }}
          appdir: "web-client"
        env:
          HD_PORT:  4000
          HD_APP_BASE: web-client
          HD_PROCFILE: web-client/Procfile